In [61]:
import pandas as pd
import numpy as np
df = pd.read_csv('train前処理.csv')

In [62]:
df.shape

(1460, 271)

In [63]:
df.columns

Index(['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'BedroomAbvGr', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtUnfSF',
       'EnclosedPorch',
       ...
       'SaleType_ConLI', 'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth',
       'SaleType_WD', 'Street_Grvl', 'Street_Pave', 'Utilities_AllPub',
       'Utilities_NoSeWa', 'SalePrice'],
      dtype='object', length=271)

In [64]:
df.loc[0,'1stFlrSF']

856.0

In [98]:
X=df.iloc[:,:270]

In [99]:
y=df['SalePrice'][:,np.newaxis]

In [100]:
y.shape

(1460, 1)

In [101]:
X.shape

(1460, 270)

In [102]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [103]:
print(X_train.shape)
print(y_train.shape)

(1022, 270)
(1022, 1)


In [204]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [205]:
lr.score(X_test, y_test)

-3900726592905.0195

In [106]:
lr.coef_

array([[  1.18191524e+06,   1.18193412e+06,   5.62917420e+00,
         -3.13832841e+03,  -2.51961748e+13,  -2.51961748e+13,
          2.40554492e+03,   3.54263249e+03,  -2.51961748e+13,
          3.37388611e+00,   1.19385405e+03,   4.84187495e+03,
          3.10314941e+01,  -5.02896522e+02,  -1.83658447e+01,
         -1.18186754e+06,   1.49275775e+03,  -1.31198415e+04,
          9.42382812e-01,   6.75373535e+01,   1.18189727e+06,
         -2.26630554e+01,   2.90194092e+01,   6.38671875e-01,
         -1.91205242e+02,   2.38758240e+01,   5.44381646e+03,
          6.50381490e+03,   3.12204590e+01,   1.92708130e+01,
          1.06236711e+03,   2.51961748e+13,   1.83181152e+01,
          3.60762451e+02,   1.07611725e+02,  -2.63947594e+02,
         -3.36240225e+11,  -3.36240237e+11,  -3.36240240e+11,
         -3.36240239e+11,  -3.36240237e+11,  -2.74833249e+11,
         -2.74833254e+11,  -2.74833166e+11,  -2.74833247e+11,
         -7.45081826e+11,  -7.45081812e+11,  -7.45081831e+11,
        

In [171]:
from sklearn.linear_model import Lasso
model_lasso = Lasso(alpha=1000)                                
model_lasso.fit(X_train, y_train) 

/Users/YK/.pyenv/versions/anaconda3-5.0.0/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


Lasso(alpha=1000, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [172]:
model_lasso.score(X_test, y_test) 

0.73488075462591174

In [173]:
model_lasso.coef_

array([  5.03852333e+01,   5.50853889e+01,   2.24756650e+01,
        -2.95613046e+03,   4.01178950e+01,   2.73657928e+01,
         0.00000000e+00,  -0.00000000e+00,   2.29937576e+01,
         6.24739698e+00,   2.97785209e+03,   0.00000000e+00,
         2.78446457e+01,   0.00000000e+00,   8.03253547e+01,
         4.16202701e+00,   0.00000000e+00,  -0.00000000e+00,
         5.08296271e-01,   8.73500874e+01,   3.66276224e+01,
        -1.42379327e+02,   3.25666728e+01,  -6.15100868e-01,
        -3.00191492e+02,  -1.51191892e+00,   4.74249732e+03,
         1.31378886e+04,   2.41986661e+01,   2.91074759e+01,
         0.00000000e+00,  -5.33862051e+00,   2.09938374e+01,
         2.82732519e+02,   1.69540655e+02,  -0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,  -0.00000000e+00,
        -0.00000000e+00,   0.00000000e+00,  -0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,  -0.00000000e+00,
        -0.00000000e+00,   0.00000000e+00,  -0.00000000e+00,
        -3.05051379e+03,

In [174]:
co=model_lasso.coef_

In [175]:
model_lasso.score(X_test, y_test) 

0.73488075462591174

In [176]:
co_sel=(co!=0)*1
co_sel

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [177]:
np.nonzero(co_sel)[0].size

37

In [170]:
len(co_sel)

270

In [275]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)       
Xa=scaler.fit_transform(X) 
from sklearn.model_selection import train_test_split
X_train_std, X_test_std, y_train, y_test = train_test_split(Xa, y, test_size = 0.3, random_state = 0)

In [248]:
from sklearn.decomposition import PCA
pca = PCA(n_components=100) 
pca.fit(X_train_std)

PCA(copy=True, iterated_power='auto', n_components=100, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [254]:
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)

In [256]:
X_test_pca

array([[ -1.01233885e+00,  -1.44625749e+00,   4.66975740e+00, ...,
         -2.57625559e-01,   4.17027410e-01,  -1.29237360e+00],
       [  5.16374122e+00,  -1.94288501e+00,   5.83862135e-01, ...,
         -4.36942575e-01,   1.10033120e+00,   7.18083819e-01],
       [  4.01703905e+00,  -9.87902593e-01,  -1.46353406e-01, ...,
         -2.51221235e+00,  -8.28233202e-01,   1.75611916e+00],
       ..., 
       [ -5.87838015e+00,  -1.56924932e+00,   2.32755927e+00, ...,
         -7.22609370e-03,  -4.52452601e-01,  -8.86312129e-01],
       [ -4.74764556e+00,   2.54869538e-01,  -1.54042380e+00, ...,
         -2.54223760e-01,   1.12996230e+00,  -1.18818044e-01],
       [ -9.27684299e+00,   2.12758957e-01,   5.11076435e+00, ...,
         -2.33357577e-01,   2.82678315e-01,  -6.35299418e-01]])

In [258]:
np.cumsum(pca.explained_variance_ratio_)

array([ 0.06586841,  0.09794793,  0.12232226,  0.14249124,  0.16061357,
        0.17711376,  0.19257885,  0.20714379,  0.22059119,  0.2336005 ,
        0.24630307,  0.258772  ,  0.27061275,  0.28215653,  0.29352031,
        0.30458034,  0.31536583,  0.32591896,  0.33617891,  0.34613917,
        0.35575479,  0.36518557,  0.37457484,  0.3837027 ,  0.39275191,
        0.4015395 ,  0.41009123,  0.41843641,  0.42668153,  0.43479501,
        0.44280552,  0.45062674,  0.45829687,  0.46583466,  0.4732691 ,
        0.48064563,  0.48793299,  0.49511332,  0.50221254,  0.50929792,
        0.51628369,  0.52316044,  0.52994987,  0.53661566,  0.54318665,
        0.54967652,  0.55611236,  0.56243441,  0.56865299,  0.5748189 ,
        0.58085919,  0.58687888,  0.59287149,  0.5987234 ,  0.60448619,
        0.61018581,  0.61587084,  0.62147048,  0.62701233,  0.63253776,
        0.63793758,  0.64323317,  0.64842691,  0.65359287,  0.65867243,
        0.66369485,  0.66869927,  0.67363801,  0.67852649,  0.68

In [259]:
pca.components_

array([[-0.10533549, -0.04522748, -0.01388844, ..., -0.01313104,
        -0.00168539,  0.00168539],
       [-0.08386976,  0.14832421, -0.01523496, ...,  0.02265879,
         0.02419407, -0.02419407],
       [ 0.17646999,  0.09170514,  0.01116126, ..., -0.06464484,
        -0.0119246 ,  0.0119246 ],
       ..., 
       [-0.04510368,  0.03835831,  0.14999105, ..., -0.04779354,
        -0.01923122,  0.01923122],
       [ 0.02136818, -0.00078254, -0.10413482, ...,  0.00057936,
         0.03520692, -0.03520692],
       [-0.00345677,  0.01233672,  0.00240635, ..., -0.03025386,
         0.064132  , -0.064132  ]])

In [269]:
from sklearn.linear_model import Lasso
model_lasso2 = Lasso(alpha=1000)                                
model_lasso2.fit(X_train_pca, y_train) 

Lasso(alpha=1000, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [270]:
model_lasso2.coef_.shape

(100,)

In [271]:
model_lasso.coef_

array([  1.43105774e+04,   4.82675235e+02,   1.26087697e+04,
        -2.62991633e+03,  -3.11995577e+03,   3.37904405e+03,
        -3.44713539e+03,   1.72720510e+03,  -5.06219759e+03,
         2.56842744e+03,   6.70151029e+02,   5.86525049e+02,
         2.51425968e+02,  -0.00000000e+00,  -8.77229026e+02,
        -1.98873134e+03,  -1.34409657e+02,  -3.54470646e+02,
        -2.19455193e+02,   6.16137050e+00,  -1.00132574e+03,
        -1.23457328e+02,  -8.67302732e+02,  -1.13963046e+03,
        -8.12957848e+01,  -1.01337098e+03,  -2.58393977e+02,
        -0.00000000e+00,  -1.39332310e+03,  -5.97201297e+02,
        -0.00000000e+00,   3.70520502e+02,  -0.00000000e+00,
         3.94130608e+03,   1.72285425e+03,  -1.39671439e+03,
         1.17639581e+03,  -7.73280375e+02,   1.49184573e+03,
         2.81458297e+02,  -1.86244054e+00,   1.60719875e+03,
        -0.00000000e+00,   4.89895062e+02,  -1.79482867e+03,
         6.40152207e+01,   1.18966541e+03,  -1.27382651e+01,
         0.00000000e+00,

In [311]:
model_lasso2.score(X_test_pca,y_test)

0.78464073777236942

In [312]:
y_test.shape

(438, 1)

In [313]:
df2=pd.read_csv('test前処理.csv')

In [314]:
df2.head()

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
0     896.0       0.0        0.0           2.0       468.0       144.0   
1    1329.0       0.0        0.0           3.0       923.0         0.0   
2     928.0     701.0        0.0           3.0       791.0         0.0   
3     926.0     678.0        0.0           3.0       602.0         0.0   
4    1280.0       0.0        0.0           2.0       263.0         0.0   

   BsmtFullBath  BsmtHalfBath  BsmtUnfSF  EnclosedPorch        ...         \
0           0.0           0.0      270.0            0.0        ...          
1           0.0           0.0      406.0            0.0        ...          
2           0.0           0.0      137.0            0.0        ...          
3           0.0           0.0      324.0            0.0        ...          
4           0.0           0.0     1017.0            0.0        ...          

   SaleType_ConLD  SaleType_ConLI  SaleType_ConLw  SaleType_New  SaleType_Oth  \
0             0.0             0.0             0.0           0.0           0.0   
1             0.0             0.0             0.0           0.0           0.0   
2             0.0             0.0             0.0           0.0           0.0   
3             0.0             0.0             0.0           0.0           0.0   
4             0.0             0.0             0.0           0.0           0.0   

   SaleType_WD  Street_Grvl  Street_Pave  Utilities_AllPub  Utilities_NoSeWa  
0          1.0          0.0          1.0               1.0               0.0  
1          1.0          0.0          1.0               1.0               0.0  
2          1.0          0.0          1.0               1.0               0.0  
3          1.0          0.0          1.0               1.0               0.0  
4          1.0          0.0          1.0               1.0               0.0  

[5 rows x 270 columns]

In [315]:
X2=df2.iloc[:,:270]

In [316]:
X2a=scaler.fit_transform(X2) 
X2_pca = pca.transform(X2a)

In [317]:
X2_pca.shape

(1459, 100)

In [318]:
An=model_lasso2.predict(X2_pca)

In [319]:
An

array([ 109441.867452  ,  178304.81042595,  187205.43360423, ...,
        169317.62150485,  116594.44823966,  232590.59073892])

In [320]:
sub=pd.read_csv('sample_submission.csv')

In [321]:
sub['SalePrice']=An

In [322]:
sub.to_csv('submission.csv')